# Generated by Django 5.0.2 on 2024-04-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
