# Generated by Django 5.0.2 on 2024-04-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_project_delete_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
    ]
